// Generated by tools/generate-miner.py. Keccak-256, 116-byte messages.
@group(0) @binding(0) var<storage, read> input: array<u32>;
@group(0) @binding(1) var<storage, read_write> result: array<atomic<u32>>;
fn rot(v: vec2<u32>, n: u32) -> vec2<u32> {
 if (n == 0u) { return v; }
 if (n == 32u) { return v.yx; }
 if (n < 32u) { return (v << vec2<u32>(n)) | (v.yx >> vec2<u32>(32u-n)); }
 let m = n-32u;
 return (v.yx << vec2<u32>(m)) | (v >> vec2<u32>(32u-m));
}
fn bswap(v: u32) -> u32 { return (v << 24u) | (v >> 24u) | ((v << 8u) & 0x00ff0000u) | ((v >> 8u) & 0x0000ff00u); }
@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {
 let nonce = input[42] + gid.x;
 var a: array<vec2<u32>,25>;
 var b: array<vec2<u32>,25>;
 var c: array<vec2<u32>,5>;
 var d: array<vec2<u32>,5>;
 for (var i=0u; i<17u; i++) { a[i]=vec2<u32>(input[2u*i],input[2u*i+1u]); }
 a[6].x=bswap(nonce);

let rc = array<vec2<u32>,24>(vec2<u32>(0x00000001u,0x00000000u),vec2<u32>(0x00008082u,0x00000000u),vec2<u32>(0x0000808au,0x80000000u),vec2<u32>(0x80008000u,0x80000000u),vec2<u32>(0x0000808bu,0x00000000u),vec2<u32>(0x80000001u,0x00000000u),vec2<u32>(0x80008081u,0x80000000u),vec2<u32>(0x00008009u,0x80000000u),vec2<u32>(0x0000008au,0x00000000u),vec2<u32>(0x00000088u,0x00000000u),vec2<u32>(0x80008009u,0x00000000u),vec2<u32>(0x8000000au,0x00000000u),vec2<u32>(0x8000808bu,0x00000000u),vec2<u32>(0x0000008bu,0x80000000u),vec2<u32>(0x00008089u,0x80000000u),vec2<u32>(0x00008003u,0x80000000u),vec2<u32>(0x00008002u,0x80000000u),vec2<u32>(0x00000080u,0x80000000u),vec2<u32>(0x0000800au,0x00000000u),vec2<u32>(0x8000000au,0x80000000u),vec2<u32>(0x80008081u,0x80000000u),vec2<u32>(0x00008080u,0x80000000u),vec2<u32>(0x80000001u,0x00000000u),vec2<u32>(0x80008008u,0x80000000u));
for (var round=0u; round<24u; round++) {
c[0] = a[0] ^ a[5] ^ a[10] ^ a[15] ^ a[20];
c[1] = a[1] ^ a[6] ^ a[11] ^ a[16] ^ a[21];
c[2] = a[2] ^ a[7] ^ a[12] ^ a[17] ^ a[22];
c[3] = a[3] ^ a[8] ^ a[13] ^ a[18] ^ a[23];
c[4] = a[4] ^ a[9] ^ a[14] ^ a[19] ^ a[24];
d[0] = c[4] ^ rot(c[1],1u);
d[1] = c[0] ^ rot(c[2],1u);
d[2] = c[1] ^ rot(c[3],1u);
d[3] = c[2] ^ rot(c[4],1u);
d[4] = c[3] ^ rot(c[0],1u);
a[0] ^= d[0];
a[1] ^= d[1];
a[2] ^= d[2];
a[3] ^= d[3];
a[4] ^= d[4];
a[5] ^= d[0];
a[6] ^= d[1];
a[7] ^= d[2];
a[8] ^= d[3];
a[9] ^= d[4];
a[10] ^= d[0];
a[11] ^= d[1];
a[12] ^= d[2];
a[13] ^= d[3];
a[14] ^= d[4];
a[15] ^= d[0];
a[16] ^= d[1];
a[17] ^= d[2];
a[18] ^= d[3];
a[19] ^= d[4];
a[20] ^= d[0];
a[21] ^= d[1];
a[22] ^= d[2];
a[23] ^= d[3];
a[24] ^= d[4];
b[0] = rot(a[0],0u);
b[10] = rot(a[1],1u);
b[20] = rot(a[2],62u);
b[5] = rot(a[3],28u);
b[15] = rot(a[4],27u);
b[16] = rot(a[5],36u);
b[1] = rot(a[6],44u);
b[11] = rot(a[7],6u);
b[21] = rot(a[8],55u);
b[6] = rot(a[9],20u);
b[7] = rot(a[10],3u);
b[17] = rot(a[11],10u);
b[2] = rot(a[12],43u);
b[12] = rot(a[13],25u);
b[22] = rot(a[14],39u);
b[23] = rot(a[15],41u);
b[8] = rot(a[16],45u);
b[18] = rot(a[17],15u);
b[3] = rot(a[18],21u);
b[13] = rot(a[19],8u);
b[14] = rot(a[20],18u);
b[24] = rot(a[21],2u);
b[9] = rot(a[22],61u);
b[19] = rot(a[23],56u);
b[4] = rot(a[24],14u);
a[0] = b[0] ^ (~b[1] & b[2]);
a[1] = b[1] ^ (~b[2] & b[3]);
a[2] = b[2] ^ (~b[3] & b[4]);
a[3] = b[3] ^ (~b[4] & b[0]);
a[4] = b[4] ^ (~b[0] & b[1]);
a[5] = b[5] ^ (~b[6] & b[7]);
a[6] = b[6] ^ (~b[7] & b[8]);
a[7] = b[7] ^ (~b[8] & b[9]);
a[8] = b[8] ^ (~b[9] & b[5]);
a[9] = b[9] ^ (~b[5] & b[6]);
a[10] = b[10] ^ (~b[11] & b[12]);
a[11] = b[11] ^ (~b[12] & b[13]);
a[12] = b[12] ^ (~b[13] & b[14]);
a[13] = b[13] ^ (~b[14] & b[10]);
a[14] = b[14] ^ (~b[10] & b[11]);
a[15] = b[15] ^ (~b[16] & b[17]);
a[16] = b[16] ^ (~b[17] & b[18]);
a[17] = b[17] ^ (~b[18] & b[19]);
a[18] = b[18] ^ (~b[19] & b[15]);
a[19] = b[19] ^ (~b[15] & b[16]);
a[20] = b[20] ^ (~b[21] & b[22]);
a[21] = b[21] ^ (~b[22] & b[23]);
a[22] = b[22] ^ (~b[23] & b[24]);
a[23] = b[23] ^ (~b[24] & b[20]);
a[24] = b[24] ^ (~b[20] & b[21]);
a[0] ^= rc[round];
}
for (var j=0u; j<8u; j++) {
 let word=bswap(select(a[j/2u].x,a[j/2u].y,(j%2u)==1u));
 if (word < input[34u+j]) { atomicMin(&result[0],nonce); return; }
 if (word > input[34u+j]) { return; }
}
}
