"""Generate single-block Keccak-256 backends from the same published permutation.
Input: 116 packed bytes + Keccak padding. No SHA3 padding (0x06) is used.
"""
from pathlib import Path
R=[0,1,62,28,27,36,44,6,55,20,3,10,43,25,39,41,45,15,21,8,18,2,61,56,14]
RC=[0x0000000000000001,0x0000000000008082,0x800000000000808a,0x8000000080008000,0x000000000000808b,0x0000000080000001,0x8000000080008081,0x8000000000008009,0x000000000000008a,0x0000000000000088,0x0000000080008009,0x000000008000000a,0x000000008000808b,0x800000000000008b,0x8000000000008089,0x8000000000008003,0x8000000000008002,0x8000000000000080,0x000000000000800a,0x800000008000000a,0x8000000080008081,0x8000000000008080,0x0000000080000001,0x8000000080008008]
def xor(items):
 out=items[0]
 for b in items[1:]: out=f'(i64.xor {out} {b})'
 return out
lines=['(module','(memory (export "memory") 1)','(data (i32.const 256) "'+''.join('\\%02x'%b for rc in RC for b in rc.to_bytes(8,'little'))+'")','(func (export "hash") $hash']
lines += [f'(local ${p}{i} i64)' for p,n in [('a',25),('b',25),('c',5),('d',5)] for i in range(n)]
lines += ['(local $round i32)']
for i in range(17): lines.append(f'(local.set $a{i} (i64.load (i32.const {i*8})))')
lines += ['(loop $rounds']
for x in range(5): lines.append(f'(local.set $c{x} '+xor([f'(local.get $a{x+5*y})' for y in range(5)])+')')
for x in range(5): lines.append(f'(local.set $d{x} (i64.xor (local.get $c{(x+4)%5}) (i64.rotl (local.get $c{(x+1)%5}) (i64.const 1))))')
for i in range(25): lines.append(f'(local.set $a{i} (i64.xor (local.get $a{i}) (local.get $d{i%5})))')
for y in range(5):
 for x in range(5):
  i=x+5*y; j=y+5*((2*x+3*y)%5)
  lines.append(f'(local.set $b{j} (i64.rotl (local.get $a{i}) (i64.const {R[i]})))')
for y in range(5):
 for x in range(5):
  a=x+5*y;b=(x+1)%5+5*y;c=(x+2)%5+5*y
  lines.append(f'(local.set $a{a} (i64.xor (local.get $b{a}) (i64.and (i64.xor (local.get $b{b}) (i64.const -1)) (local.get $b{c}))))')
lines += ['(local.set $a0 (i64.xor (local.get $a0) (i64.load (i32.add (i32.const 256) (i32.shl (local.get $round) (i32.const 3))))))','(local.set $round (i32.add (local.get $round) (i32.const 1)))','(br_if $rounds (i32.lt_u (local.get $round) (i32.const 24)))',')']
for i in range(4): lines.append(f'(i64.store (i32.const {192+8*i}) (local.get $a{i}))')
lines += [')', '''(func $valid (result i32)
(local $i i32) (local $a i32) (local $b i32)
(loop $compare
 (local.set $a (i32.load8_u (i32.add (i32.const 192) (local.get $i))))
 (local.set $b (i32.load8_u (i32.add (i32.const 160) (local.get $i))))
 (if (i32.ne (local.get $a) (local.get $b)) (then (return (i32.lt_u (local.get $a) (local.get $b)))))
 (local.set $i (i32.add (local.get $i) (i32.const 1)))
 (br_if $compare (i32.lt_u (local.get $i) (i32.const 32))))
(i32.const 0))
(func $bswap (param $v i32) (result i32)
(i32.or (i32.or (i32.shl (local.get $v) (i32.const 24)) (i32.shr_u (local.get $v) (i32.const 24)))
(i32.or (i32.and (i32.shl (local.get $v) (i32.const 8)) (i32.const 16711680)) (i32.and (i32.shr_u (local.get $v) (i32.const 8)) (i32.const 65280)))))
(func (export "mine") (param $nonce i32) (param $count i32) (result i64)
(local $i i32)
(loop $search
 (if (i32.ge_u (local.get $i) (local.get $count)) (then (return (i64.const -1))))
 (i32.store (i32.const 48) (call $bswap (local.get $nonce)))
 (call $hash)
 (if (call $valid) (then (return (i64.extend_i32_u (local.get $nonce)))))
 (local.set $nonce (i32.add (local.get $nonce) (i32.const 1)))
 (local.set $i (i32.add (local.get $i) (i32.const 1)))
 (br $search))
(i64.const -1))
)''']
# Function identifiers precede export clauses in WAT.
lines[3]='(func $hash (export "hash")'
Path('site/miner/keccak.wat').write_text('\n'.join(lines)+'\n')
w=['// Generated by tools/generate-miner.py. Keccak-256, 116-byte messages.',
'''@group(0) @binding(0) var<storage, read> input: array<u32>;
@group(0) @binding(1) var<storage, read_write> result: array<atomic<u32>>;
fn rot(v: vec2<u32>, n: u32) -> vec2<u32> {
 if (n == 0u) { return v; }
 if (n == 32u) { return v.yx; }
 if (n < 32u) { return (v << vec2<u32>(n)) | (v.yx >> vec2<u32>(32u-n)); }
 let m = n-32u;
 return (v.yx << vec2<u32>(m)) | (v >> vec2<u32>(32u-m));
}
fn bswap(v: u32) -> u32 { return (v << 24u) | (v >> 24u) | ((v << 8u) & 0x00ff0000u) | ((v >> 8u) & 0x0000ff00u); }
@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {
 let nonce = input[42] + gid.x;
 var a: array<vec2<u32>,25>;
 var b: array<vec2<u32>,25>;
 var c: array<vec2<u32>,5>;
 var d: array<vec2<u32>,5>;
 for (var i=0u; i<17u; i++) { a[i]=vec2<u32>(input[2u*i],input[2u*i+1u]); }
 a[6].x=bswap(nonce);
''', 'let rc = array<vec2<u32>,24>('+','.join(f'vec2<u32>(0x{r&0xffffffff:08x}u,0x{r>>32:08x}u)' for r in RC)+');','for (var round=0u; round<24u; round++) {']
for x in range(5): w.append(f'c[{x}] = '+' ^ '.join(f'a[{x+5*y}]' for y in range(5))+';')
for x in range(5): w.append(f'd[{x}] = c[{(x+4)%5}] ^ rot(c[{(x+1)%5}],1u);')
for i in range(25): w.append(f'a[{i}] ^= d[{i%5}];')
for y in range(5):
 for x in range(5):
  i=x+5*y; j=y+5*((2*x+3*y)%5)
  w.append(f'b[{j}] = rot(a[{i}],{R[i]}u);')
for y in range(5):
 for x in range(5): w.append(f'a[{x+5*y}] = b[{x+5*y}] ^ (~b[{(x+1)%5+5*y}] & b[{(x+2)%5+5*y}]);')
w+=['a[0] ^= rc[round];','}', '''for (var j=0u; j<8u; j++) {
 let word=bswap(select(a[j/2u].x,a[j/2u].y,(j%2u)==1u));
 if (word < input[34u+j]) { atomicMin(&result[0],nonce); return; }
 if (word > input[34u+j]) { return; }
}
}''']
Path('site/miner/keccak.wgsl').write_text('\n'.join(w)+'\n')
